{% set name = "pgrouting" %}
{% set version = "3.7.2" %}
{% set sha256 = "fb0d9ef3247a95166e172412734fda9746233912601a4891cbcf02fe87764140" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pgrouting/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 953e3368b172fe81881128a6ec078f6b31cf52196b773dfc05df4237bb9c5e26

build:
  number: 0
  script:
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja install
  # osx build disabled due to issue GH18
  skip: true  # [win or osx]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cgal
    - cmake
    - ninja
    - perl
    - pkg-config
    - postgresql
    - postgis
  run:
    - {{ pin_compatible('cgal', exact=True) }}
    - postgis
    - postgresql

about:
  home: http://github.com/pgrouting/pgrouting
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: pgRouting extends PostGIS/PostgreSQL geospatial database to provide geospatial routing and other network analysis functionality.

  doc_url: https://docs.pgrouting.org
  dev_url: https://github.com/pgrouting/pgrouting

extra:
  recipe-maintainers:
    - akrherz
    - sodre
